name: Deploy SageMaker Pipelines
on:
  workflow_call:

jobs:
  deploy:
    name: Deploy Pipelines
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tfvars:
          - vars/iris/iris.tfvars
          - vars/propensity/propensity.tfvars

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install boto3 sagemaker jinja2

      - name: Deploy SageMaker pipeline
        run: |
          echo "Deploying pipeline using config: ${{ matrix.tfvars }}"
          python scripts/deploy_pipeline.py --config "${{ matrix.tfvars }}"
